spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ON_SECRET
    password: ON_SECRET
    hikari:
      connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect